package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;

public class TelaPerfil extends javax.swing.JDialog { //faltam imagens para icones...

    /**
     * Creates new form TelaPerfil
     */
    public TelaPerfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public JButton getjButtonMudarSenha() {
        return jButtonMudarSenha;
    }

    public JButton getjButtonEditEmail() {
        return jButtonEditEmail;
    }

    public JButton getjButtonEditarEndereco() {
        return jButtonEditarEndereco;
    }
    
    public JLabel getjLabelEmail() {
        return jLabelEmail;
    }

    public JLabel getjLabelFoto() {
        return jLabelFoto;
    }

    public JLabel getjLabelNome() {
        return jLabelNome;
    }

    public JList<String> getjListEnderecos() {
        return jListEnderecos;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFoto = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelTituloEmail = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jScrollPaneEnderecos = new javax.swing.JScrollPane();
        jListEnderecos = new javax.swing.JList<>();
        jLabelEnderecos = new javax.swing.JLabel();
        jButtonEditEmail = new javax.swing.JButton();
        jButtonMudarSenha = new javax.swing.JButton();
        jButtonEditarEndereco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelFoto.setText("foto");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNome.setText("NOME");

        jLabelTituloEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTituloEmail.setText("E-Mail:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEmail.setText("example@email.com");

        jListEnderecos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jListEnderecos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEnderecos.setViewportView(jListEnderecos);

        jLabelEnderecos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEnderecos.setText("Endereços:");

        jButtonEditEmail.setText("Edit");

        jButtonMudarSenha.setText("Mudar senha");

        jButtonEditarEndereco.setText("Editar endereço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTituloEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditEmail))
                            .addComponent(jButtonMudarSenha)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelEnderecos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditarEndereco)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addComponent(jScrollPaneEnderecos)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEnderecos)
                            .addComponent(jButtonEditarEndereco)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTituloEmail)
                            .addComponent(jLabelEmail)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonEditEmail)
                                .addGap(3, 3, 3)))
                        .addComponent(jButtonMudarSenha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPerfil dialog = new TelaPerfil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditEmail;
    private javax.swing.JButton jButtonEditarEndereco;
    private javax.swing.JButton jButtonMudarSenha;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnderecos;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTituloEmail;
    private javax.swing.JList<String> jListEnderecos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneEnderecos;
    // End of variables declaration//GEN-END:variables
}
